baseURL = "https://planet.jerad.xyz"
#CanonifyURLs=true

languageCode = "en-us"
theme = "ramium"

title = "Planet Jerad"
disqusShortname = "irJERAD"
googleAnalytics = ""
summaryLength = 40
pluralizeListTitles = false
enableemoji = false

[params]
    description = "it's a whole new world will it keep together or splinter away"
    googleSearch = ""
    adsense = ""
    showDate = true # make false if dont want to show date
    math = false # best to enable this in the front matter of a page
    githubProfile = "irJerad/planet/"

    tagsInHome = 40
    sectionsInHome = 5
    paginatePostsPerPage = 5
    paginateTagsPerPage = 6

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "This Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Tags"
                url = "/tags/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "All Sections"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Posts"
                url = "/posts/"
                weight = 3

    [[menu.main]]
        name = "A Collective Awareness"
        url = "/a_collective_conscious/"
        weight = 3

    [[menu.main]]
        name = "Notes"
        url = "/notes/"
        weight = 4
    
    [[menu.main]]
        name = "Author"
        url = "/author/"
        weight = 5